### ISSUE TITLE
npm install fails with SyntaxError

### ISSUE THREAD

**Issue by pnosko** [substack/node-archy#2]
When trying to install bower, or when running `npm install archy`, the following error is thrown:

```
npm http GET https://registry.npmjs.org/archy
npm http 200 https://registry.npmjs.org/archy
npm ERR! registry error parsing json
npm ERR! SyntaxError: Unexpected token _
npm ERR! __utmc=251085184; __utmz=251085184.1398704766.2.2.utmcsr=yandex|utmccn=(organic)|utmcmd=organic; optimizelyPendingLogEvents=%5B%5D; __utma=209680785.856385113.1398704766.1398704766.1398704766.1; __utmb=209680785.1.9.1398704769929; __utmc=209680785; __utmz=209680785.1398704766.1.1.utmcsr=yandex|utmccn=(organic)|utmcmd=organics","dirFastly-FF: cache-fra1233-FRA, cache-fra1228-FRAtest"},"devDependencies":{"tap":"~0.2.3"},"scripts":{"test":"tap test"},"repository":{"type":"git","url":"git://github.com/substack/node-archy.git"},"keywords":["hierarchy","npm ls","unicode","pretty","print"],"author":{"name":"James Halliday","email":"mail@substack.net","url":"http://substack.net"},"license":"MIT/X11","engine":{"node":">=0.4"},"_npmUser":{"name":"substack","email":"mail@substack.net"},"_id":"archy@0.0.0","dependencies":{},"engines":{"node":"*"},"_engineSupported":true,"_npmVersion":"1.0.106","_nodeVersion":"v0.4.12","_defaultsLoaded":true,"dist":{"shasum":"fcc82f2916a8307969b368e8617646b41697c37b","tarball":"http://registry.npmjs.org/archy/-/archy-0.0.0.tgz"},"maintainers":[{"name":"substack","email":"mail@substack.net"}]},"0.0.1":{"name":"archy","version":"0.0.1","description":"render nested hierarchies `npm ls` style with unicode pipes","main":"index.js","directories":{"lib":".","example":"example","test":"test"},"devDependencies":{"tap":"~0.2.3"},"scripts":{"test":"tap test"},"repository":{"type":"git","url":"git://github.com/substack/node-archy.git"},"keywords":["hierarchy","npm ls","unicode","pretty","print"],"author":{"name":"James Halliday","email":"mail@substack.net","url":"http://substack.net"},"license":"MIT/X11","engine":{"node":">=0.4"},"_npmUser":{"name":"substack","email":"mail@substack.net"},"_id":"archy@0.0.1","dependencies":{},"engines":{"node":"*"},"_engineSupported":true,"_npmVersion":"1.0.106","_nodeVersion":"v0.4.12","_defaultsLoaded":true,"dist":{"shasum":"8c26dc5741db90792ccdbd34c57311cb3003ea1b","tarball":"http://registry.npmjs.org/archy/-/archy-0.0.1.tgz"},"maintainers":[{"name":"substack","email":"mail@substack.net"}]},"0.0.2":{"name":"archy","version":"0.0.2","description":"render nested hierarchies `npm ls` style with unicode pipes","main":"index.js","directories":{"lib":".","example":"example","test":"test"},"devDependencies":{"tap":"~0.2.3"},"scripts":{"test":"tap test"},"repository":{"type":"git","url":"git://github.com/substack/node-archy.git"},"keywords":["hierarchy","npm ls","unicode","pretty","print"],"author":{"name":"James Halliday","email":"mail@substack.net","url":"http://substack.net"},"license":"MIT/X11","engine":{"node":">=0.4"},"_npmUser":{"name":"substack","email":"mail@substack.net"},"_id":"archy@0.0.2","dependencies":{},"engines":{"node":"*"},"_engineSupported":true,"_npmVersion":"1.0.106","_nodeVersion":"v0.4.12","_defaultsLoaded":true,"dist":{"shasum":"910f43bf66141fc335564597abc189df44b3d35e","tarball":"http://registry.npmjs.org/archy/-/archy-0.0.2.tgz"},"maintainers":[{"name":"substack","email":"mail@substack.net"}]}},"readme":null,"maintainers":[{"name":"substack","email":"mail@substack.net"}],"time":{"modified":"2013-11-28T16:13:38.735Z","created":"2012-03-08T21:18:36.039Z","0.0.0":"2012-03-08T21:18:54.909Z","0.0.1":"2012-03-08T23:09:26.726Z","0.0.2":"2012-03-08T23:09:46.988Z"},"author":{"name":"James Halliday","email":"mail@substack.net","url":"http://substack.net"},"repository":{"type":"git","url":"git://github.com/substack/node-archy.git"},"users":{"tellnes":true,"conradz":true},"_attachments":{}}
npm ERR!     at Object.parse (native)
npm ERR!     at RegClient.<anonymous> (/mnt/sdc1/thealphanerd/node/node-v0.10.26-linux-x64/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:203:23)
npm ERR!     at Request.self.callback (/mnt/sdc1/thealphanerd/node/node-v0.10.26-linux-x64/lib/node_modules/npm/node_modules/request/request.js:123:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/mnt/sdc1/thealphanerd/node/node-v0.10.26-linux-x64/lib/node_modules/npm/node_modules/request/request.js:893:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/mnt/sdc1/thealphanerd/node/node-v0.10.26-linux-x64/lib/node_modules/npm/node_modules/request/request.js:844:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
```

This is reproducible on both Mac OS X and Windows 8.
Is there a workaround for this please?

**Comment by sheerun** [comment]
It seems to be fixed. You can close it
